# Generated by Django 5.2.1 on 2025-05-27 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_funcionario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='ni',
            field=models.IntegerField(blank=True, error_messages={'unique': 'Número de identificação (NI) já está cadastrado.'}, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Telefone inválido. Ex: (11)91234-5678', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
